# Generated by Django 2.2.3 on 2019-07-15 14:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidate_candidateparty_candidateposition_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['position__position_level', 'user__last_name', 'user__first_name'], 'verbose_name': 'candidate', 'verbose_name_plural': 'candidates'},
        ),
        migrations.AlterModelOptions(
            name='candidateparty',
            options={'ordering': ['party_name'], 'verbose_name': 'party', 'verbose_name_plural': 'parties'},
        ),
        migrations.AlterModelOptions(
            name='candidateposition',
            options={'ordering': ['position_level', 'position_name'], 'verbose_name': 'candidate position', 'verbose_name_plural': 'candidate positions'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['candidate__position__position_level', 'user__last_name', 'user__first_name'], 'verbose_name': 'vote', 'verbose_name_plural': 'votes'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='core.CandidateParty'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='core.CandidatePosition'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateparty',
            name='party_name',
            field=models.CharField(default=None, max_length=32, unique=True, verbose_name='party name'),
        ),
        migrations.AddField(
            model_name='candidateposition',
            name='position_level',
            field=models.PositiveSmallIntegerField(default=32767, verbose_name='position level'),
        ),
        migrations.AddField(
            model_name='candidateposition',
            name='position_name',
            field=models.CharField(default=None, max_length=32, unique=True, verbose_name='position name'),
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='core.Candidate'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_cipher',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, unique=True),
        ),
        migrations.AddIndex(
            model_name='candidateparty',
            index=models.Index(fields=['party_name'], name='core_candid_party_n_0036f5_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'candidate'], name='core_vote_user_id_4ec4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateposition',
            index=models.Index(fields=['position_name'], name='core_candid_positio_cbea74_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['user'], name='core_candid_user_id_6883e4_idx'),
        ),
    ]
