# Generated by Django 2.2.12 on 2020-05-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_candidate_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['position__position_level', 'party__party_name'], 'verbose_name': 'candidate', 'verbose_name_plural': 'candidates'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['candidate__position__position_level', 'candidate__party__party_name'], 'verbose_name': 'vote', 'verbose_name_plural': 'votes'},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_cipher',
        ),
    ]
