# Generated by Django 2.2.12 on 2020-05-22 08:46

import core.models.user_models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200520_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'indexes': [],
                'constraints': [],
                'proxy': True,
                'verbose_name': 'Admin',
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.user_models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
            ],
            options={
                'indexes': [],
                'constraints': [],
                'proxy': True,
                'verbose_name': 'Voter',
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.user_models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.user_models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'voter'), (1, 'admin')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='VoterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='date_updated')),
                ('batch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.Batch')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.Section')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='voter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'verbose_name_plural': 'voter_profiles',
                'verbose_name': 'voter_profile',
            },
        ),
        migrations.AddIndex(
            model_name='voterprofile',
            index=models.Index(fields=['user'], name='core_voterp_user_id_1b2c96_idx'),
        ),
    ]
