# Generated by Django 2.2.12 on 2020-05-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200522_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='voter_profiles', to='core.Batch'),
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='voter_profiles', to='core.Section'),
        ),
    ]
