# Generated by Django 2.2.12 on 2020-05-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200522_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='date_updated')),
                ('name', models.CharField(default=None, max_length=32, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'election',
                'verbose_name_plural': 'elections',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='candidateparty',
            name='party_name',
            field=models.CharField(default=None, max_length=32, verbose_name='party name'),
        ),
        migrations.AlterField(
            model_name='candidateposition',
            name='position_name',
            field=models.CharField(default=None, max_length=32, verbose_name='position name'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['name'], name='core_electi_name_5d75fc_idx'),
        ),
        migrations.AddField(
            model_name='batch',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.Election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.Election'),
        ),
        migrations.AddField(
            model_name='candidateparty',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_parties', to='core.Election'),
        ),
        migrations.AddField(
            model_name='candidateposition',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_positions', to='core.Election'),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.Election'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateparty',
            unique_together={('party_name', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='candidateposition',
            unique_together={('position_name', 'election')},
        ),
    ]
