# Generated by Django 2.2.13 on 2020-06-08 07:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200529_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['position__position_level', 'party__party_name', 'user__last_name', 'user__first_name'], 'verbose_name': 'candidate', 'verbose_name_plural': 'candidates'},
        ),
        migrations.AddField(
            model_name='candidateposition',
            name='max_num_selected_candidates',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='max_num_selected_candidates'),
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='voter_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
