# Generated by Django 2.2.13 on 2020-06-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_candidateposition_target_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterprofile',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidateposition',
            name='target_batches',
            field=models.ManyToManyField(blank=True, default=None, related_name='candidate_positions', to='core.Batch'),
        ),
    ]
