# Generated by Django 2.2.13 on 2020-07-09 06:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200616_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['election', 'position__position_level', 'party__party_name', 'user__last_name', 'user__first_name'], 'verbose_name': 'candidate', 'verbose_name_plural': 'candidates'},
        ),
        migrations.AlterModelOptions(
            name='candidateparty',
            options={'ordering': ['election', 'party_name'], 'verbose_name': 'party', 'verbose_name_plural': 'parties'},
        ),
        migrations.AlterModelOptions(
            name='candidateposition',
            options={'ordering': ['election', 'position_level', 'position_name'], 'verbose_name': 'candidate position', 'verbose_name_plural': 'candidate positions'},
        ),
        migrations.AlterModelOptions(
            name='voterprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'voter profile', 'verbose_name_plural': 'voter profiles'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='election',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.Election'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidateposition',
            name='max_num_selected_candidates',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Number of Selectable Candidates'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.Candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
