# Generated by Django 2.2.13 on 2020-07-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200710_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.Election'),
        ),
    ]
