# Generated by Django 2.2.3 on 2019-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=None, unique=True, verbose_name='year')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'verbose_name': 'batch',
                'ordering': ['year'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['year'], name='accounts_ba_year_357035_idx'),
        ),
    ]
