# Generated by Django 2.2.3 on 2019-07-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section_name'], 'verbose_name': 'section', 'verbose_name_plural': 'batches'},
        ),
        migrations.AddField(
            model_name='section',
            name='section_name',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='section_name'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.SmallIntegerField(unique=True, verbose_name='year'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_name'], name='accounts_se_section_55525a_idx'),
        ),
    ]
