# Generated by Django 2.2.3 on 2019-07-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190702_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.SmallIntegerField(default=0, unique=True, verbose_name='year'),
        ),
    ]
