# Generated by Django 2.2.3 on 2019-07-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190708_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.Batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.Section'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.SmallIntegerField(default=None, unique=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(default=None, max_length=15, unique=True, verbose_name='section_name'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
    ]
